spring.application.name=biblioteca-api

# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5433/biblioteca
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate

# Troca update por validate ? o Flyway cuida do schema agora
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false